### ISSUE TITLE
Dropdown submenu

### ISSUE THREAD

**Issue by stefanmcds-mnt** [italia/design-laravel-theme#4]
Salve,
è possibile avere un esempio di dropdown submenu

**Comment by alfredotranchedone** [comment]
non credo sia previsto un sottomenu per i dropdown

**Comment by francescozaia** [comment]
> non credo sia previsto un sottomenu per i dropdown

Confermo. Preferiremmo evitare di avere troppi livelli di menu. Al limite si può utilizzare un "[megamenu](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/megamenu/#classico-con-intestazione-e-link-more)" con intestazioni.

**Comment by robertogallea** [comment]
Credo sia possibile chiudere l'issue, grazie @alfredotranchedone e @francescozaia per avere risposto prima di me
